// Project Data

const PROJECTS = [
	{
		id: 1,
		name: 'SarahLiz Fitness',
		img: '/assets/images/sarahliz_fitness.png',
		translateX: 0,
		translateZ: 4000,
		rotateX: 0,
		rotateY: 0,
		rotateZ: 0.45,
		// Title
		translateTitleX: 0,
		translateTitleY: -180,
		translateTitleZ: 4000,
		rotateTitleX: 0,
		rotateTitleY: 0,
		rotateTitleZ: 0.46,
		// Tech Moons
		tech1: '/assets/images/react-logo.png',
		tech2: '/assets/images/node-logo.png',
		translateTechX: 0,
		translateTechY: 0,
		translateTechZ: 4000,
		rotateTechX: -3.5,
		rotateTechY: 4.5,
		rotateTechZ: 5.5,
	},
	{
		id: 2,
		name: 'Robinhood Clone',
		img: '/assets/images/robinhood-clone.png',
		tech2: '/assets/images/firebase-logo.jpg',
		translateX: 4000,
		translateZ: 0,
		rotateX: 0.45,
		rotateY: 0,
		rotateZ: 0,
		// Title
		translateTitleX: 4000,
		translateTitleY: -180,
		translateTitleZ: 0,
		rotateTitleX: 0.48,
		rotateTitleY: 1.56,
		rotateTitleZ: -0,
		// Tech Moons
		tech1: '/assets/images/node-logo.png',
		translateTechX: 4000,
		translateTechY: 0,
		translateTechZ: 0,
		rotateTechX: 0,
		rotateTechY: 0,
		rotateTechZ: 0.45,
	},
	{
		id: 3,
		name: 'Videography Portfolio',
		img: '/assets/images/videography-portfolio.png',
		translateX: 0,
		translateZ: -4000,
		rotateX: -0,
		rotateY: -0.4,
		rotateZ: -0.45,
		// Title
		translateTitleX: 25,
		translateTitleY: -190,
		translateTitleZ: -4000,
		rotateTitleX: 0.05,
		rotateTitleY: 3.1,
		rotateTitleZ: 0.47,
		// Tech Moons
		tech1: '/assets/images/node-logo.png',
		translateTechX: 0,
		translateTechY: 0,
		translateTechZ: -4000,
		rotateTechX: 0,
		rotateTechY: 0,
		rotateTechZ: 0,
	},
	{
		id: 4,
		name: 'This Website',
		img: '/assets/images/stars.jpg',
		translateX: -4000,
		translateZ: 0,
		rotateX: -0,
		rotateY: -0.4,
		rotateZ: -0.45,
		// Title
		translateTitleX: -4000,
		translateTitleY: -180,
		translateTitleZ: 26,
		rotateTitleX: -1.36,
		rotateTitleY: -1.5,
		rotateTitleZ: -0.9,
		// Tech Moons
		tech1: '/assets/images/node-logo.png',
		translateTechX: 0,
		translateTechY: 0,
		translateTechZ: -4000,
		rotateTechX: 0,
		rotateTechY: 0,
		rotateTechZ: 0,
	},
];
